### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by heungni1** [Belserich/glowing-chainsaw#1]
Js or not?

**Comment by Belserich** [comment]
what do you mean

**Comment by Belserich** [comment]
creating the navigation using js?

**Comment by heungni1** [comment]
yes, exactly

**Comment by Belserich** [comment]
https://stackoverflow.com/questions/31954089/html-css-navigation-bar-on-multiple-pages

**Comment by Belserich** [comment]
yeap
